# Generated by Django 5.1.3 on 2025-02-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='home.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(related_name='pedidos', through='home.ItemPedido', to='home.produto'),
        ),
    ]
